services:
  flask:
    image: flask-app
    container_name: flask_compose
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_compose
    ports:
      - "7070:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask

  db:
    image: postgres:16
    container_name: db_compose
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_compose
volumes:
  db_data:
